<?php

return [
    'load_const' => '读取常量',
    'push_const' => '压入常量',
    'push_string' => '压入字符串',
    'push_array' => '压入数组',
    'push_number' => '压入数字',
    'pop' => '出栈',
    'reference' => '引用',
    'dereference' => '解除引用',
    'assign' => '赋值',
    'jnz' => '条件跳转',
    'jmp' => '无条件跳转',
    'global' => 'global',
    'array_item' => '数组初始化',
    'array_dim_fetch' => '数组元素获取',
    'list_assign' => '列表赋值',
    'boolean_not' => '取非',
    'plus' => '相加',
    'minus' => '相减',
    'mul' => '相乘',
    'div' => '相除',
    'mod' => '求余数',
    'concat' => '字符串链接',
    'greater' => '大于',
    'greater_or_equal' => '大于等于',
    'equal' => '相等',
    'identical' => '完全相同',
    'func_call' => '调用函数',
    'include' => 'include',
    'cast_bool' => '转换为bool',
    'property_fetch' => '获取类属性',
    'empty' => 'empty',
    'exit' => 'exit',
    'reset' => 'reset',
    'next' => 'next',
    'push_error_level' => '抑制错误显示',
    'pop_error_level' => '抑制错误显示结束',
];